name: ci

on:
  push:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64"]
    runs-on: docker-${{ matrix.arch }}
    container:
      image: docker.aimmac23.com/aim/base-builder:latest
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - run: podman login -u ${{ vars.REGISTRY_USERNAME  }} -p ${{ secrets.REGISTRY_SECRET  }} docker.aimmac23.com
      - run: podman build  -t docker.aimmac23.com/aim/conan-server-${{ matrix.arch }} --net host .
      - run: ./check-container-startup.sh docker.aimmac23.com/aim/conan-server-${{ matrix.arch }}
      - run: podman push docker.aimmac23.com/aim/conan-server-${{ matrix.arch }}

  trivy:
    needs:
      - build
    runs-on: docker-arm64
    container:
      image: docker.io/aquasec/trivy
      env:
        TRIVY_PASSWORD: ${{ secrets.REGISTRY_SECRET }}
    steps:
      - run: trivy image docker.aimmac23.com/aim/conan-server-arm64 --username ${{ secrets.REGISTRY_USERNAME }}
