name: ci

on:
  push:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm64", "arm32", "amd64"]
    runs-on: docker-${{ matrix.arch }}
    container: docker.aimmac23.com/aim/base-builder:latest
    steps:
      - uses: actions/checkout@v4
      - run: podman login -u ${{ vars.REGISTRY_USERNAME  }} -p ${{ secrets.REGISTRY_SECRET  }} docker.aimmac23.com
      - run: podman build  -t docker.aimmac23.com/aim/conan-server-${{ matrix.arch }} .
      - run: podman push docker.aimmac23.com/aim/conan-server-${{ matrix.arch }}

  multiarch:
    runs-on: docker
    needs:
      - build
    container: docker.aimmac23.com/aim/base-builder:latest
    steps:
      - run: podman login -u ${{ vars.REGISTRY_USERNAME  }} -p ${{ secrets.REGISTRY_SECRET  }} docker.aimmac23.com
      - run: podman pull docker.aimmac23.com/aim/conan-server-arm64
      - run: podman pull docker.aimmac23.com/aim/conan-server-arm32
      - run: podman pull docker.aimmac23.com/aim/conan-server-amd64
      - run: podman manifest create docker.aimmac23.com/aim/conan-server --amend docker.aimmac23.com/aim/conan-server-arm64 --amend docker.aimmac23.com/aim/conan-server-arm32 --amend docker.aimmac23.com/aim/conan-server-amd64
      - run: podman manifest push docker.aimmac23.com/aim/conan-server
